# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://PaddyWu.github.io
date_format: "ordinal"
title: PaddyWuBIT
subtitle: "Code can change the world, We change code!"
description: "信息管理与信息系统"
keywords: Python,SQL,SPSS,Stata,Excel/Word/PPT,ML
timezone: China/BeiJing
encoding: "utf-8"
side_bar_repo_limit: 5
repository: PaddyWuPython/PaddyWu.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 访问统计
    busuanzi:
        enabled: true
        start_date: 2023-07-15
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]

# ---------------- #
#      Author      #
# ---------------- #
author: Paddy Wu
organization: 
organization_url: 
github_username: PaddyWu
location: BeiJing, China
email: 1120193070@bit.edu.cn

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  # -
  #   href: /management/
  #   label: 技术管理

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: piterjia
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
# 参考：https://www.ppkanshu.com/index.php/post/4158.html
gitalk:
    owner: piterjia(original author)
    repo: blog-comments
    clientID: db388e97352eeaeafb30
    clientSecret: 14e93c15b35acb7ec88633e88c94154bdf8e847c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
